Repository input-output-hk/vit-servicing-station, pull requests merged in 2020-08, with the labels that each got.

#77 docker for tests and server
  docker/master/Dockerfile
  docker/master/block0.bin
  docker/master/database.db
  docker/soak_tests/Dockerfile
Labels: test

#60 Vit station cli
  Cargo.lock
  Cargo.toml
  README.md
  vit-servicing-station-cli/Cargo.toml
  vit-servicing-station-cli/src/app.rs
  vit-servicing-station-cli/src/main.rs
  vit-servicing-station-lib/Cargo.toml
  vit-servicing-station-lib/src/db/migrations.rs
  vit-servicing-station-lib/src/db/mod.rs
  vit-servicing-station-lib/src/db/models/api_tokens.rs
  vit-servicing-station-lib/src/db/queries/api_tokens.rs
  vit-servicing-station-lib/src/lib.rs
  vit-servicing-station-lib/src/v0/api_token.rs
  vit-servicing-station-lib/src/v0/endpoints/funds/handlers.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/routes.rs
  vit-servicing-station-lib/src/v0/endpoints/proposals/handlers.rs
Labels: enhancement

#73 Async graphql update i64
  Cargo.lock
  vit-servicing-station-lib/Cargo.toml
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/proposals.rs
Labels: enhancement

#79 Voteplans - rename chain_committee_end to chain_committee_end_time
  vit-servicing-station-lib/src/db/models/voteplans.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/routes.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/voteplans.rs
  vit-servicing-station-tests/resources/graphql_requests/templates/fund_by_id.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/fund_by_id_wrong_arg_type.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/fund_field_does_not_exist.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/funds.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_alias.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_aliases.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_by_id.graphql.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_comment.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_field_does_not_exist.txt
  vit-servicing-station-tests/src/common/data/generator.rs
  vit-servicing-station-tests/src/common/db/mod.rs
Labels: Refactor

#80 Cli init db command
  vit-servicing-station-cli/src/api_token.rs
  vit-servicing-station-cli/src/app.rs
  vit-servicing-station-cli/src/init_db.rs
  vit-servicing-station-cli/src/main.rs
  vit-servicing-station-lib/src/db/migrations.rs
  vit-servicing-station-lib/src/db/queries/api_tokens.rs
  vit-servicing-station-lib/src/v0/api_token.rs
  vit-servicing-station-lib/src/v0/endpoints/funds/handlers.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/routes.rs
  vit-servicing-station-lib/src/v0/endpoints/proposals/handlers.rs
Labels: enhancement

#82 Enable/Disable api tokens feature
  vit-servicing-station-lib/src/server/settings/config.rs
  vit-servicing-station-lib/src/server/settings/default.rs
  vit-servicing-station-lib/src/v0/endpoints/mod.rs
  vit-servicing-station-lib/src/v0/mod.rs
  vit-servicing-station-server/src/main.rs
  vit-servicing-station-tests/src/common/startup/server/bootstrap.rs
  vit-servicing-station-tests/src/common/startup/server/command.rs
  vit-servicing-station-tests/src/common/startup/server/settings.rs
  vit-servicing-station-tests/src/tests/rest/token.rs
Labels: enhancement

#81 Cli backup db file before operations
  Cargo.lock
  vit-servicing-station-cli/Cargo.toml
  vit-servicing-station-cli/src/api_token.rs
  vit-servicing-station-cli/src/csv/loaders.rs
  vit-servicing-station-cli/src/db_utils.rs
Labels: enhancement
