Repository input-output-hk/vit-servicing-station, pull requests merged in 2020-09, with the labels that each got.

#86 Implemented signal handling for gracefully shutdown the server
  Cargo.lock
  vit-servicing-station-lib/Cargo.toml
  vit-servicing-station-lib/src/server/bootstrapping.rs
  vit-servicing-station-lib/src/server/mod.rs
  vit-servicing-station-lib/src/server/signals.rs
Labels: enhancement

#87 Implemented lazy block0 load
  vit-servicing-station-lib/src/server/exit_codes.rs
  vit-servicing-station-lib/src/v0/context.rs
  vit-servicing-station-lib/src/v0/endpoints/genesis/handlers.rs
  vit-servicing-station-server/src/main.rs
  vit-servicing-station-tests/src/tests/bootstrap/arguments/block0.rs
  vit-servicing-station-tests/src/tests/bootstrap/arguments/mod.rs
  vit-servicing-station-tests/src/tests/rest/genesis.rs
Labels: Priority - High, enhancement

#88 Added additional data fields to fund/proposal
  diesel.toml
  migrations/2020-05-22-112032_initial/up.sql
  vit-servicing-station-cli/src/csv/models.rs
  vit-servicing-station-lib/src/db/models/funds.rs
  vit-servicing-station-lib/src/db/models/proposals.rs
  vit-servicing-station-lib/src/db/schema.rs
  vit-servicing-station-lib/src/db/views_schema.rs
  vit-servicing-station-lib/src/server/settings/config.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/routes.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/funds.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/proposals.rs
  vit-servicing-station-tests/resources/graphql_requests/templates/fund_by_id.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/funds.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_by_id.graphql.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposals.txt
  vit-servicing-station-tests/src/common/data/generator.rs
  vit-servicing-station-tests/src/common/db/mod.rs
  vit-servicing-station-tests/src/tests/rest/proposals.rs
Labels: enhancement

#92 [Test] fixed incompatibility in load test after jortestkit update
  vit-servicing-station-tests/src/tests/non_functional/mod.rs
Labels: test
