Repository input-output-hk/vit-servicing-station, pull requests merged in 2020-12, with the labels that each got.

#102 Release workflow
  .github/workflows/release.yml
  ci/release-info.py
  ci/strip-own-version-from-cargo-lock.pl
  vit-servicing-station-lib/Cargo.lock
  vit-servicing-station-server/Cargo.lock
Labels: CI

#104 Tracing
  Cargo.lock
  Cargo.toml
  logging-lib/Cargo.toml
  logging-lib/src/config.rs
  logging-lib/src/lib.rs
  logging-lib/src/messages.rs
  logging-lib/src/methods.rs
  vit-servicing-station-lib/Cargo.toml
  vit-servicing-station-lib/src/lib.rs
  vit-servicing-station-lib/src/logging/mod.rs
  vit-servicing-station-lib/src/server/settings/config.rs
  vit-servicing-station-lib/src/v0/api_token.rs
  vit-servicing-station-lib/src/v0/mod.rs
  vit-servicing-station-server/Cargo.toml
  vit-servicing-station-server/src/main.rs
  vit-servicing-station-tests/src/common/startup/server/settings.rs
Labels: enhancement

#107 Updated async-graphql to version 2
  Cargo.lock
  vit-servicing-station-lib/Cargo.toml
  vit-servicing-station-lib/src/v0/endpoints/graphql/handlers/mod.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/routes.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/funds.rs
  vit-servicing-station-lib/src/v0/errors.rs
  vit-servicing-station-tests/src/tests/graphql/proposals.rs
Labels: dependencies

#108 Make test gql queries be readable
  vit-servicing-station-lib/src/v0/endpoints/graphql/routes.rs
Labels: cleaning, test

#93 [Tests] Db init and load tests for cli
  Cargo.lock
  vit-servicing-station-tests/Cargo.toml
  vit-servicing-station-tests/src/common/cli/commands/csv_data/load.rs
  vit-servicing-station-tests/src/common/cli/commands/csv_data/mod.rs
  vit-servicing-station-tests/src/common/cli/commands/db/init.rs
  vit-servicing-station-tests/src/common/cli/commands/db/mod.rs
  vit-servicing-station-tests/src/common/cli/commands/mod.rs
  vit-servicing-station-tests/src/common/data/csv_converter.rs
  vit-servicing-station-tests/src/common/data/generator/arbitrary.rs
  vit-servicing-station-tests/src/common/data/generator/mod.rs
  vit-servicing-station-tests/src/common/data/generator/snapshot.rs
  vit-servicing-station-tests/src/common/data/generator/voting.rs
  vit-servicing-station-tests/src/common/data/mod.rs
  vit-servicing-station-tests/src/common/startup/mod.rs
  vit-servicing-station-tests/src/tests/bootstrap/arguments/block0.rs
  vit-servicing-station-tests/src/tests/bootstrap/mod.rs
  vit-servicing-station-tests/src/tests/cli/db.rs
  vit-servicing-station-tests/src/tests/cli/load.rs
  vit-servicing-station-tests/src/tests/cli/mod.rs
  vit-servicing-station-tests/src/tests/cli/token.rs
  vit-servicing-station-tests/src/tests/rest/cors.rs
Labels: test

#109 Removed leftover scripts from previous log lib
  log-processing-scrips/README.md
  log-processing-scrips/average_request_response_time.py
Labels: cleaning
