Repository input-output-hk/vit-servicing-station, pull requests merged in 2020-05, with the labels that each got.

#1 Actions - add api doc deploy to gh-pages
  .github/workflows/api_gh.yml
Labels: documentation, enhancement

#5 Base server implementation with REST endpoints
  Cargo.lock
  Cargo.toml
  resources/v0/chain_data.json
  src/main.rs
  src/server.rs
  src/settings/mod.rs
  src/v0/context.rs
  src/v0/endpoints/chain_data/handlers.rs
  src/v0/endpoints/chain_data/logic.rs
  src/v0/endpoints/chain_data/mod.rs
  src/v0/endpoints/chain_data/routes.rs
  src/v0/endpoints/genesis/handlers.rs
  src/v0/endpoints/genesis/mod.rs
  src/v0/endpoints/genesis/routes.rs
  src/v0/endpoints/mod.rs
  src/v0/mod.rs
Labels: Priority - High, enhancement

#6 Added rust (check, test, lints) github actions script
  .github/workflows/main.yml
Labels: enhancement

#9 diesel and graphql integration
  .env
  .github/workflows/main.yml
  Cargo.lock
  Cargo.toml
  README.md
  diesel.toml
  migrations/2020-05-22-112032_initial/down.sql
  migrations/2020-05-22-112032_initial/up.sql
  src/db/mod.rs
  src/db/schema.rs
  src/main.rs
  src/v0/context.rs
  src/v0/endpoints/genesis/handlers.rs
  src/v0/endpoints/genesis/routes.rs
  src/v0/endpoints/graphql/handlers.rs
  src/v0/endpoints/graphql/mod.rs
  src/v0/endpoints/graphql/routes.rs
  src/v0/endpoints/graphql/schema.rs
  src/v0/endpoints/mod.rs
Labels: enhancement
