Repository input-output-hk/vit-servicing-station, pull requests merged in 2020-07, with the labels that each got.

#36 Missing deserialize default for Tls config: Fix #32
  vit-servicing-station-lib/src/server/settings/config.rs
  vit-servicing-station-lib/src/server/settings/default.rs
Labels: bug

#39 Make output config files pretty
  vit-servicing-station-lib/src/server/settings/config.rs
Labels: bug

#40 [Tests] Added test project
  .github/workflows/main.yml
  Cargo.lock
  Cargo.toml
  vit-servicing-station-lib/src/v0/api_token.rs
  vit-servicing-station-tests/Cargo.toml
  vit-servicing-station-tests/askama.toml
  vit-servicing-station-tests/build.rs
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_by_id.graphql.txt
  vit-servicing-station-tests/src/common/clients/graphql.rs
  vit-servicing-station-tests/src/common/clients/mod.rs
  vit-servicing-station-tests/src/common/clients/rest.rs
  vit-servicing-station-tests/src/common/data/mod.rs
  vit-servicing-station-tests/src/common/db/mod.rs
  vit-servicing-station-tests/src/common/mod.rs
  vit-servicing-station-tests/src/common/paths.rs
  vit-servicing-station-tests/src/common/server.rs
  vit-servicing-station-tests/src/common/startup/db.rs
  vit-servicing-station-tests/src/common/startup/mod.rs
  vit-servicing-station-tests/src/common/startup/server.rs
  vit-servicing-station-tests/src/lib.rs
  vit-servicing-station-tests/src/tests/graphql/mod.rs
  vit-servicing-station-tests/src/tests/graphql/proposals.rs
  vit-servicing-station-tests/src/tests/mod.rs
  vit-servicing-station-tests/src/tests/rest/mod.rs
  vit-servicing-station-tests/src/tests/rest/proposals.rs
Labels: test

#37 Gracefully exit and error reporting on application startup
  vit-servicing-station-lib/src/server/settings/config.rs
  vit-servicing-station-lib/src/v0/context.rs
  vit-servicing-station-lib/src/v0/endpoints/genesis/handlers.rs
  vit-servicing-station-server/src/main.rs
Labels: bug

#43 Added a health endpoint
  vit-servicing-station-lib/src/v0/endpoints/health/handlers.rs
  vit-servicing-station-lib/src/v0/endpoints/health/mod.rs
  vit-servicing-station-lib/src/v0/endpoints/health/routes.rs
  vit-servicing-station-lib/src/v0/endpoints/mod.rs
Labels: enhancement

#45 Use health endpoint
  vit-servicing-station-tests/src/common/clients/rest.rs
  vit-servicing-station-tests/src/common/server.rs
  vit-servicing-station-tests/src/common/startup/mod.rs
  vit-servicing-station-tests/src/common/startup/server.rs
  vit-servicing-station-tests/src/tests/graphql/proposals.rs
  vit-servicing-station-tests/src/tests/rest/proposals.rs
Labels: test

#44 [Tests] in_file_settings parameter bootstrap tests
  Cargo.lock
  vit-servicing-station-tests/Cargo.toml
  vit-servicing-station-tests/src/common/startup/mod.rs
  vit-servicing-station-tests/src/common/startup/server.rs
  vit-servicing-station-tests/src/common/startup/server/bootstrap.rs
  vit-servicing-station-tests/src/common/startup/server/command.rs
  vit-servicing-station-tests/src/common/startup/server/mod.rs
  vit-servicing-station-tests/src/common/startup/server/settings.rs
  vit-servicing-station-tests/src/tests/bootstrap/mod.rs
  vit-servicing-station-tests/src/tests/bootstrap/parameters.rs
  vit-servicing-station-tests/src/tests/mod.rs
Labels: test

#51 Implemented application exit error codes
  vit-servicing-station-lib/src/server/exit_codes.rs
  vit-servicing-station-lib/src/server/mod.rs
  vit-servicing-station-lib/src/server/settings/config.rs
  vit-servicing-station-server/src/main.rs
  vit-servicing-station-tests/src/tests/bootstrap/parameters.rs
Labels: enhancement

#38 Skip api token filter for playground
  Cargo.lock
  vit-servicing-station-lib/Cargo.toml
  vit-servicing-station-lib/src/db/models/vote_options.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/mod.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/playground.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/routes.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/funds.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/mod.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/proposals.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/vote_options.rs
  vit-servicing-station-lib/src/v0/endpoints/mod.rs
  vit-servicing-station-lib/src/v0/mod.rs
Labels: bug

#54 Use OutputJson for i64 graphql atributtes
  vit-servicing-station-lib/src/db/models/proposals.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/proposals.rs
Labels: enhancement

#55 Playground endpoint considerations
  README.md
Labels: documentation

#57 Expanded version v0 api docs with rest endpoints and schema objects
  doc/api/v0.yaml
Labels: documentation

#61 Enforce end paths for rest endpoints
  vit-servicing-station-lib/src/v0/endpoints/funds/routes.rs
  vit-servicing-station-lib/src/v0/endpoints/genesis/routes.rs
  vit-servicing-station-lib/src/v0/endpoints/health/routes.rs
  vit-servicing-station-lib/src/v0/endpoints/proposals/routes.rs
Labels: bug

#59 [Tests] Db builder
  Cargo.lock
  vit-servicing-station-lib/src/db/models/api_tokens.rs
  vit-servicing-station-lib/src/db/models/proposals.rs
  vit-servicing-station-lib/src/v0/api_token.rs
  vit-servicing-station-tests/Cargo.toml
  vit-servicing-station-tests/src/common/data/generator.rs
  vit-servicing-station-tests/src/common/data/mod.rs
  vit-servicing-station-tests/src/common/db/mod.rs
  vit-servicing-station-tests/src/common/startup/db.rs
  vit-servicing-station-tests/src/common/startup/mod.rs
  vit-servicing-station-tests/src/tests/bootstrap/mod.rs
  vit-servicing-station-tests/src/tests/graphql/proposals.rs
  vit-servicing-station-tests/src/tests/rest/proposals.rs
Labels: test

#46 [Tests] Rest endpoint tests
  vit-servicing-station-tests/src/common/clients/graphql.rs
  vit-servicing-station-tests/src/common/clients/rest.rs
  vit-servicing-station-tests/src/common/data/generator.rs
  vit-servicing-station-tests/src/common/db/mod.rs
  vit-servicing-station-tests/src/common/startup/db.rs
  vit-servicing-station-tests/src/tests/rest/funds.rs
  vit-servicing-station-tests/src/tests/rest/genesis.rs
  vit-servicing-station-tests/src/tests/rest/mod.rs
  vit-servicing-station-tests/src/tests/rest/proposals.rs
Labels: test

#50 [Tests] Token validation tests
  vit-servicing-station-tests/src/common/clients/rest.rs
  vit-servicing-station-tests/src/common/data/generator.rs
  vit-servicing-station-tests/src/common/data/mod.rs
  vit-servicing-station-tests/src/tests/rest/mod.rs
  vit-servicing-station-tests/src/tests/rest/token.rs
Labels: test

#68 Test connection before returning pool
  vit-servicing-station-lib/src/db/mod.rs
Labels: bug

#66 [Tests] Graphql tests
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_alias.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_aliases.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_by_id.graphql.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_comment.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_cycle.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_field_does_not_exist.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_fragments.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_required_fields.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_without_argument.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposals.txt
  vit-servicing-station-tests/src/common/clients/graphql/mod.rs
  vit-servicing-station-tests/src/common/clients/graphql/templates.rs
  vit-servicing-station-tests/src/common/clients/rest.rs
  vit-servicing-station-tests/src/common/data/generator.rs
  vit-servicing-station-tests/src/tests/graphql/proposals.rs
Labels: test

#64 [Tests] test case with incorrect block0 and db_url
  vit-servicing-station-tests/src/common/data/generator.rs
  vit-servicing-station-tests/src/tests/bootstrap/parameters.rs
Labels: test

#69 [Tests] Rest cors testing
  vit-servicing-station-tests/src/common/clients/rest.rs
  vit-servicing-station-tests/src/common/startup/server/bootstrap.rs
  vit-servicing-station-tests/src/common/startup/server/settings.rs
  vit-servicing-station-tests/src/tests/rest/cors.rs
  vit-servicing-station-tests/src/tests/rest/mod.rs
Labels: test

#63 Load input file before dumping
  vit-servicing-station-lib/src/server/settings/config.rs
  vit-servicing-station-server/src/main.rs
Labels: bug

#56 [Tests] more tests for Cmd line parameters
  vit-servicing-station-tests/src/common/server.rs
  vit-servicing-station-tests/src/common/startup/server/mod.rs
  vit-servicing-station-tests/src/common/startup/server/settings.rs
  vit-servicing-station-tests/src/tests/bootstrap/arguments/address.rs
  vit-servicing-station-tests/src/tests/bootstrap/arguments/block0.rs
  vit-servicing-station-tests/src/tests/bootstrap/arguments/db_url.rs
  vit-servicing-station-tests/src/tests/bootstrap/arguments/in_settings.rs
  vit-servicing-station-tests/src/tests/bootstrap/arguments/mod.rs
  vit-servicing-station-tests/src/tests/bootstrap/arguments/out_settings.rs
  vit-servicing-station-tests/src/tests/bootstrap/mod.rs
Labels: test

#71 [Test] Funds graphql tests
  vit-servicing-station-tests/resources/graphql_requests/templates/fund_by_id.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/fund_by_id_wrong_arg_type.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/fund_field_does_not_exist.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/fund_required_fields.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/fund_without_argument.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/funds.txt
  vit-servicing-station-tests/src/common/clients/graphql/mod.rs
  vit-servicing-station-tests/src/common/clients/graphql/templates.rs
  vit-servicing-station-tests/src/common/data/generator.rs
  vit-servicing-station-tests/src/tests/graphql/funds.rs
  vit-servicing-station-tests/src/tests/graphql/mod.rs
Labels: test

#70 Implemented file logging and logging configuration
  Cargo.lock
  vit-servicing-station-lib/Cargo.toml
  vit-servicing-station-lib/src/server/log.rs
  vit-servicing-station-lib/src/server/mod.rs
  vit-servicing-station-lib/src/server/settings/config.rs
  vit-servicing-station-lib/src/server/settings/default.rs
  vit-servicing-station-server/Cargo.toml
  vit-servicing-station-server/src/main.rs
Labels: enhancement
