Repository input-output-hk/vit-servicing-station, pull requests merged in 2021-04, with the labels that each got.

#154 Added proposer rewards to challenges for rewards automation
  vit-servicing-station-lib/migrations/2020-05-22-112032_setup_db/up.sql
  vit-servicing-station-lib/src/db/models/challenges.rs
  vit-servicing-station-lib/src/db/schema.rs
  vit-servicing-station-tests/src/common/data/csv_converter.rs
  vit-servicing-station-tests/src/common/data/generator/arbitrary.rs
  vit-servicing-station-tests/src/common/data/generator/voting/plan.rs
  vit-servicing-station-tests/src/common/data/generator/voting/template/arbitrary.rs
  vit-servicing-station-tests/src/common/data/generator/voting/template/mod.rs
  vit-servicing-station-tests/src/common/db/mod.rs
  vit-servicing-station-tests/src/tests/rest/funds.rs
Labels: api, enhancement

#157 eccoxide: add to Cargo.toml
  vit-servicing-station-lib/Cargo.toml
Labels: dependencies

#158 Make service version part of server config
  Cargo.lock
  vit-servicing-station-lib/src/server/settings/config.rs
  vit-servicing-station-lib/src/server/settings/default.rs
  vit-servicing-station-lib/src/server/settings/mod.rs
  vit-servicing-station-lib/src/v0/context.rs
  vit-servicing-station-server/src/main.rs
  vit-servicing-station-tests/src/common/startup/server/bootstrap.rs
  vit-servicing-station-tests/src/common/startup/server/command.rs
  vit-servicing-station-tests/src/tests/bootstrap/arguments/address.rs
Labels: enhancement

#160 Update dependencies and versions in cargo.lock
  Cargo.lock
Labels: dependencies

#162 Rest API additions
  doc/api/v0.yaml
  vit-servicing-station-lib/migrations/2020-05-22-112032_setup_db/up.sql
  vit-servicing-station-lib/src/db/models/funds.rs
  vit-servicing-station-lib/src/db/schema.rs
  vit-servicing-station-tests/src/common/data/csv_converter.rs
  vit-servicing-station-tests/src/common/data/generator/arbitrary.rs
  vit-servicing-station-tests/src/common/data/generator/voting/plan.rs
  vit-servicing-station-tests/src/common/db/mod.rs
  vit-servicing-station-tests/src/tests/cli/load.rs
Labels: api

#163 [Tests] allow to specify more than one voteplan in tests
  vit-servicing-station-tests/src/common/data/generator/voting/plan.rs
  vit-servicing-station-tests/src/tests/cli/load.rs
Labels: test
