Repository input-output-hk/vit-servicing-station, pull requests merged in 2021-02, with the labels that each got.

#122 Bump api version to 0.1.1
  doc/api/v0.yaml
Labels: cleaning

#124 API: fix voteplan field chain_committee_end_time
  doc/api/v0.yaml
Labels: api

#126 Tracing subscribers fixes
  vit-servicing-station-server/src/main.rs
Labels: bug

#128 expose fund_id field
  vit-servicing-station-tests/src/common/data/generator/voting.rs
Labels: test

#129 Expose voting content in vote plan generator
  vit-servicing-station-tests/src/common/data/generator/arbitrary.rs
  vit-servicing-station-tests/src/common/data/generator/mod.rs
  vit-servicing-station-tests/src/common/data/generator/voting/mod.rs
  vit-servicing-station-tests/src/common/data/generator/voting/plan.rs
  vit-servicing-station-tests/src/common/data/generator/voting/template/arbitrary.rs
  vit-servicing-station-tests/src/common/data/generator/voting/template/external.rs
  vit-servicing-station-tests/src/common/data/generator/voting/template/mod.rs
  vit-servicing-station-tests/src/common/data/mod.rs
  vit-servicing-station-tests/src/tests/cli/load.rs
  vit-servicing-station-tests/src/tests/non_functional/mod.rs
Labels: test

#130 Expose voting content
  Cargo.lock
  vit-servicing-station-tests/Cargo.toml
  vit-servicing-station-tests/src/common/data/generator/arbitrary.rs
  vit-servicing-station-tests/src/common/data/generator/voting/mod.rs
  vit-servicing-station-tests/src/common/data/generator/voting/plan.rs
  vit-servicing-station-tests/src/common/data/generator/voting/template/arbitrary.rs
  vit-servicing-station-tests/src/common/data/generator/voting/template/external.rs
  vit-servicing-station-tests/src/common/data/generator/voting/template/mod.rs
  vit-servicing-station-tests/src/common/data/mod.rs
  vit-servicing-station-tests/src/tests/cli/load.rs
Labels: test

#131 Cleanup challenges
  vit-servicing-station-lib/src/db/models/challenges.rs
  vit-servicing-station-lib/src/db/queries/challenges.rs
Labels: cleaning

#132 Challenge type and Proposal polymorphism in the API
  .github/workflows/api.yml
  .spectral.yaml
  doc/api/v0.yaml
Labels: api

#133 Proposal challenge type
  vit-servicing-station-cli/src/api_token.rs
  vit-servicing-station-cli/src/csv/models.rs
  vit-servicing-station-lib/migrations/2020-05-22-112032_setup_db/down.sql
  vit-servicing-station-lib/migrations/2020-05-22-112032_setup_db/up.sql
  vit-servicing-station-lib/src/db/models/mod.rs
  vit-servicing-station-lib/src/db/models/proposals.rs
  vit-servicing-station-lib/src/db/models/proposals_challenge_info.rs
  vit-servicing-station-lib/src/db/schema.rs
  vit-servicing-station-lib/src/db/views_schema.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/routes.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/proposals.rs
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_by_id.graphql.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_required_fields.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_without_argument.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposals.txt
  vit-servicing-station-tests/src/common/data/csv_converter.rs
  vit-servicing-station-tests/src/common/data/generator/arbitrary.rs
  vit-servicing-station-tests/src/common/data/generator/voting/plan.rs
  vit-servicing-station-tests/src/common/data/generator/voting/template/arbitrary.rs
  vit-servicing-station-tests/src/common/data/generator/voting/template/external.rs
  vit-servicing-station-tests/src/common/data/generator/voting/template/mod.rs
  vit-servicing-station-tests/src/common/db/mod.rs
Labels: enhancement

#134 Challenge type variadic fields refactor
  vit-servicing-station-cli/src/csv/models.rs
  vit-servicing-station-lib/migrations/2020-05-22-112032_setup_db/down.sql
  vit-servicing-station-lib/migrations/2020-05-22-112032_setup_db/up.sql
  vit-servicing-station-lib/src/db/models/challenges.rs
  vit-servicing-station-lib/src/db/models/mod.rs
  vit-servicing-station-lib/src/db/models/proposals.rs
  vit-servicing-station-lib/src/db/models/proposals_challenge_info.rs
  vit-servicing-station-lib/src/db/queries/challenges.rs
  vit-servicing-station-lib/src/db/schema.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/routes.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/challenge.rs
  vit-servicing-station-lib/src/v0/endpoints/proposals/handlers.rs
  vit-servicing-station-tests/resources/graphql_requests/templates/fund_by_id.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/funds.txt
  vit-servicing-station-tests/src/common/data/csv_converter.rs
  vit-servicing-station-tests/src/common/data/generator/arbitrary.rs
  vit-servicing-station-tests/src/common/data/generator/voting/plan.rs
  vit-servicing-station-tests/src/common/data/generator/voting/template/arbitrary.rs
  vit-servicing-station-tests/src/common/data/generator/voting/template/external.rs
  vit-servicing-station-tests/src/common/data/generator/voting/template/mod.rs
  vit-servicing-station-tests/src/common/data/mod.rs
  vit-servicing-station-tests/src/common/db/mod.rs
  vit-servicing-station-tests/src/common/startup/db.rs
  vit-servicing-station-tests/src/tests/rest/proposals.rs
Labels: enhancement

#140 do not scale proposals impact score
  vit-servicing-station-tests/src/common/data/generator/voting/plan.rs
  vit-servicing-station-tests/src/common/data/generator/voting/template/mod.rs
Labels: test

#141 Database schema improvements for proposal polymorphism
  vit-servicing-station-cli/src/csv/loaders.rs
  vit-servicing-station-cli/src/csv/models.rs
  vit-servicing-station-lib/migrations/2020-05-22-112032_setup_db/down.sql
  vit-servicing-station-lib/migrations/2020-05-22-112032_setup_db/up.sql
  vit-servicing-station-lib/src/db/models/challenges.rs
  vit-servicing-station-lib/src/db/models/proposals.rs
  vit-servicing-station-lib/src/db/models/proposals/community_choice.rs
  vit-servicing-station-lib/src/db/models/proposals/simple.rs
  vit-servicing-station-lib/src/db/queries/proposals.rs
  vit-servicing-station-lib/src/db/schema.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/handlers/mod.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/handlers/proposals.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/routes.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/proposals.rs
  vit-servicing-station-lib/src/v0/endpoints/proposals/handlers.rs
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_by_id.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_without_argument.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposals.txt
  vit-servicing-station-tests/src/common/clients/rest.rs
  vit-servicing-station-tests/src/common/data/csv_converter.rs
  vit-servicing-station-tests/src/common/data/generator/arbitrary.rs
  vit-servicing-station-tests/src/common/data/generator/snapshot.rs
  vit-servicing-station-tests/src/common/data/generator/voting/plan.rs
  vit-servicing-station-tests/src/common/data/generator/voting/template/arbitrary.rs
  vit-servicing-station-tests/src/common/data/generator/voting/template/mod.rs
  vit-servicing-station-tests/src/common/data/mod.rs
  vit-servicing-station-tests/src/common/db/mod.rs
  vit-servicing-station-tests/src/common/startup/db.rs
  vit-servicing-station-tests/src/tests/cli/load.rs
  vit-servicing-station-tests/src/tests/graphql/proposals.rs
  vit-servicing-station-tests/src/tests/rest/proposals.rs
Labels: enhancement

#145 Fix challenge-proposal relation on plan generation
  vit-servicing-station-tests/src/common/data/generator/voting/plan.rs
Labels: bug

#146 Challenge type filtering fix
  vit-servicing-station-tests/src/common/data/generator/voting/plan.rs
Labels: bug

#143 Drop GraphQl support
  Cargo.lock
  README.md
  vit-servicing-station-lib/Cargo.toml
  vit-servicing-station-lib/src/v0/endpoints/graphql/handlers/funds.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/handlers/mod.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/handlers/proposals.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/mod.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/playground.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/routes.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/challenge.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/funds.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/mod.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/proposals.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/voteplans.rs
  vit-servicing-station-lib/src/v0/endpoints/mod.rs
  vit-servicing-station-lib/src/v0/errors.rs
  vit-servicing-station-tests/askama.toml
  vit-servicing-station-tests/resources/graphql_requests/templates/fund_by_id.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/fund_by_id_wrong_arg_type.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/fund_field_does_not_exist.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/fund_required_fields.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/fund_without_argument.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/funds.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_alias.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_aliases.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_by_id.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_comment.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_cycle.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_field_does_not_exist.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_fragments.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_required_fields.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposal_without_argument.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/proposals.txt
  vit-servicing-station-tests/src/common/clients/graphql/mod.rs
  vit-servicing-station-tests/src/common/clients/graphql/templates.rs
  vit-servicing-station-tests/src/common/clients/mod.rs
  vit-servicing-station-tests/src/common/clients/rest.rs
  vit-servicing-station-tests/src/common/server.rs
  vit-servicing-station-tests/src/tests/graphql/funds.rs
  vit-servicing-station-tests/src/tests/graphql/mod.rs
  vit-servicing-station-tests/src/tests/graphql/proposals.rs
  vit-servicing-station-tests/src/tests/mod.rs
  vit-servicing-station-tests/src/tests/non_functional/mod.rs
Labels: cleaning
