Repository input-output-hk/vit-servicing-station, pull requests merged in 2021-03, with the labels that each got.

#148 Fix challenge generation
  vit-servicing-station-tests/src/common/data/generator/voting/plan.rs
Labels: bug

#150 [Test] Expose challenges mut
  vit-servicing-station-tests/src/common/data/generator/snapshot.rs
  vit-servicing-station-tests/src/common/data/generator/voting/plan.rs
  vit-servicing-station-tests/src/tests/cli/load.rs
Labels: test

#151 Service version endpoint
  vit-servicing-station-lib/src/server/exit_codes.rs
  vit-servicing-station-lib/src/server/settings/config.rs
  vit-servicing-station-lib/src/server/settings/mod.rs
  vit-servicing-station-lib/src/v0/context.rs
  vit-servicing-station-lib/src/v0/endpoints/mod.rs
  vit-servicing-station-lib/src/v0/endpoints/service_version/handlers.rs
  vit-servicing-station-lib/src/v0/endpoints/service_version/logic.rs
  vit-servicing-station-lib/src/v0/endpoints/service_version/mod.rs
  vit-servicing-station-lib/src/v0/endpoints/service_version/routes.rs
  vit-servicing-station-lib/src/v0/endpoints/service_version/schemas.rs
  vit-servicing-station-lib/src/v0/mod.rs
  vit-servicing-station-server/src/main.rs
  vit-servicing-station-tests/src/common/clients/rest.rs
  vit-servicing-station-tests/src/common/startup/server/bootstrap.rs
  vit-servicing-station-tests/src/tests/bootstrap/arguments/address.rs
  vit-servicing-station-tests/src/tests/rest/mod.rs
  vit-servicing-station-tests/src/tests/rest/service_version.rs
Labels: enhancement

#152 Clippy happy in rust 1.51
  Cargo.lock
  vit-servicing-station-cli/src/api_token.rs
  vit-servicing-station-cli/src/app.rs
  vit-servicing-station-cli/src/csv/loaders.rs
  vit-servicing-station-cli/src/init_db.rs
  vit-servicing-station-cli/src/main.rs
  vit-servicing-station-lib/src/db/migrations.rs
  vit-servicing-station-lib/src/db/mod.rs
  vit-servicing-station-lib/src/db/models/api_tokens.rs
  vit-servicing-station-lib/src/db/models/challenges.rs
  vit-servicing-station-lib/src/db/models/funds.rs
  vit-servicing-station-lib/src/db/models/proposals.rs
  vit-servicing-station-lib/src/db/models/voteplans.rs
  vit-servicing-station-lib/src/db/queries/api_tokens.rs
  vit-servicing-station-lib/src/db/queries/challenges.rs
  vit-servicing-station-lib/src/db/queries/funds.rs
  vit-servicing-station-lib/src/db/queries/proposals.rs
  vit-servicing-station-lib/src/db/queries/voteplans.rs
  vit-servicing-station-lib/src/server/exit_codes.rs
  vit-servicing-station-lib/src/utils/serde.rs
  vit-servicing-station-lib/src/v0/api_token.rs
  vit-servicing-station-lib/src/v0/context.rs
  vit-servicing-station-server/src/main.rs
  vit-servicing-station-tests/src/common/data/csv_converter.rs
  vit-servicing-station-tests/src/common/data/generator/arbitrary.rs
  vit-servicing-station-tests/src/common/data/generator/snapshot.rs
  vit-servicing-station-tests/src/common/data/mod.rs
  vit-servicing-station-tests/src/common/db/mod.rs
  vit-servicing-station-tests/src/common/startup/db.rs
  vit-servicing-station-tests/src/common/startup/server/command.rs
  vit-servicing-station-tests/src/tests/bootstrap/arguments/db_url.rs
  vit-servicing-station-tests/src/tests/bootstrap/arguments/in_settings.rs
  vit-servicing-station-tests/src/tests/bootstrap/arguments/out_settings.rs
Labels: cleaning
