Repository input-output-hk/vit-servicing-station, pull requests merged in 2021-01, with the labels that each got.

#110 CI improvements
  .github/workflows/main.yml
  .github/workflows/test.yml
  vit-servicing-station-cli/src/api_token.rs
Labels: CI

#111 Security audit workflow
  .github/workflows/audit.yml
  Cargo.lock
Labels: CI

#115 [Test] private vote data generation
  vit-servicing-station-tests/src/common/data/generator/voting.rs
Labels: test

#118 add challenge_url to challenges
  doc/api/v0.yaml
  resources/tests/csvs/challenges.csv
  vit-servicing-station-lib/migrations/2020-05-22-112032_setup_db/up.sql
  vit-servicing-station-lib/src/db/models/challenges.rs
  vit-servicing-station-lib/src/db/schema.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/routes.rs
  vit-servicing-station-lib/src/v0/endpoints/graphql/schema/challenge.rs
  vit-servicing-station-tests/resources/graphql_requests/templates/fund_by_id.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/fund_by_id_wrong_arg_type.txt
  vit-servicing-station-tests/resources/graphql_requests/templates/funds.txt
  vit-servicing-station-tests/src/common/data/csv_converter.rs
  vit-servicing-station-tests/src/common/data/generator/arbitrary.rs
  vit-servicing-station-tests/src/common/db/mod.rs
Labels: Priority - High, enhancement

#123 [Test] voting_power_info now point to voting_start date
  vit-servicing-station-tests/src/common/data/generator/voting.rs
  vit-servicing-station-tests/src/tests/cli/load.rs
Labels: test
