Repository input-output-hk/vit-servicing-station, pull requests merged in 2021-07, with the labels that each got.

#173 assert cmd update and fixed some minor error message
  Cargo.lock
  vit-servicing-station-tests/Cargo.toml
  vit-servicing-station-tests/src/common/data/generator/voting/plan.rs
Labels: test

#175 Remove fund legacy field rewards_info
  resources/tests/csvs/funds.csv
  vit-servicing-station-lib/migrations/2020-05-22-112032_setup_db/up.sql
  vit-servicing-station-lib/src/db/models/funds.rs
  vit-servicing-station-lib/src/db/schema.rs
  vit-servicing-station-tests/src/common/data/csv_converter.rs
  vit-servicing-station-tests/src/common/data/generator/arbitrary.rs
  vit-servicing-station-tests/src/common/data/generator/voting/plan.rs
  vit-servicing-station-tests/src/common/db/mod.rs
Labels: cleaning

#176 Refactored cli error system
  Cargo.lock
  vit-servicing-station-cli/Cargo.toml
  vit-servicing-station-cli/src/api_token.rs
  vit-servicing-station-cli/src/app.rs
  vit-servicing-station-cli/src/csv/loaders.rs
  vit-servicing-station-cli/src/init_db.rs
  vit-servicing-station-cli/src/task.rs
Labels: enhancement
